all: staging-archives/$(THING).tar.gz

include GNUmakefile.base

staging-archives/$(THING).tar.gz: $(prefix)/$(THING)
	(cd $(prefix); tar czf - $(THING)) > $@

$(prefix)/$(THING): staging/$(THING) $(prefix)
	cp -r $< $@

staging/$(THING): source-archives/$(THING).tar.gz  staging
	cat $< | (cd staging; tar xzf -)
	cd staging/$(THING)/doc; $(MAKE); $(MAKE) clean


