all: staging-archives/$(THING).tar.gz

include GNUmakefile.base

staging-archives/$(THING).tar.gz: binary-archives/$(THING).bz2 $(prefix)
	cat $< | (cd $(prefix); tar xjf -)
	chmod 0777 $(prefix)/$(THING)
	(cd $(prefix); tar czf - $(THING)) > $@
