#VERSION=$(subst openmcl-,,$(THING))
VERSION=$(THING)

all: staging-archives/$(THING).tar.gz

include GNUmakefile.base

staging-archives/$(THING).tar.gz: binary-archives/$(VERSION).tar.gz $(prefix)
	cat $< | (cd $(prefix); tar xzf -; mv ccl $(THING))
	(cd $(prefix); tar czf - $(THING)) > $@
